// ─── Overview / KPIs ───────────────────────────────────────────────────────
export const kpis = {
  totalAudience: "3.4M",
  audienceGrowth: "+12.5%",
  pendingRevenue: "$24,500",
  activeCollabs: 8,
  avgEngagement: "8.2%",
  engagementGrowth: "+1.2%",
};

// ─── Platform Stats ─────────────────────────────────────────────────────────
export const platforms = [
  {
    id: "youtube",
    name: "YouTube",
    icon: "youtube",
    color: "#FF0000",
    bg: "bg-red-500/10",
    border: "hover:border-red-500/50",
    followers: "1.2M",
    followerLabel: "Subs",
    weekGrowth: "+5k this week",
    metricLabel: "Revenue",
    metricValue: "$4.2k",
    views: "18.4M",
    watchHours: "312k hrs",
    avgViewDuration: "6m 42s",
    ctr: "4.8%",
  },
  {
    id: "instagram",
    name: "Instagram",
    icon: "instagram",
    color: "#E1306C",
    bg: "bg-pink-500/10",
    border: "hover:border-pink-500/50",
    followers: "850k",
    followerLabel: "Followers",
    weekGrowth: "+2.1k this week",
    metricLabel: "Reach",
    metricValue: "2.4M",
    views: "9.1M",
    watchHours: "—",
    avgViewDuration: "—",
    ctr: "3.2%",
  },
  {
    id: "x",
    name: "X (Twitter)",
    icon: "x",
    color: "#ffffff",
    bg: "bg-gray-500/10",
    border: "hover:border-gray-500/50",
    followers: "1.35M",
    followerLabel: "Followers",
    weekGrowth: "+12k this week",
    metricLabel: "Impressions",
    metricValue: "15M",
    views: "15M",
    watchHours: "—",
    avgViewDuration: "—",
    ctr: "2.1%",
  },
];

// ─── Revenue Chart Data ──────────────────────────────────────────────────────
export const revenueData = [
  { month: "Jan", adsense: 6200, brandDeals: 5800, total: 12000 },
  { month: "Feb", adsense: 7400, brandDeals: 11600, total: 19000 },
  { month: "Mar", adsense: 6800, brandDeals: 8200, total: 15000 },
  { month: "Apr", adsense: 9200, brandDeals: 12800, total: 22000 },
  { month: "May", adsense: 11000, brandDeals: 17000, total: 28000 },
  { month: "Jun", adsense: 10200, brandDeals: 13800, total: 24000 },
  { month: "Jul", adsense: 13500, brandDeals: 18500, total: 32000 },
];

// ─── AI Suggestions ──────────────────────────────────────────────────────────
export const aiSuggestions = [
  {
    id: 1,
    title: '"A Day in the Life: Managing Brands at 22"',
    reason:
      "Based on a 40% spike in watch time on your last vlog and high DM volume asking about your workflow.",
    platforms: ["YouTube", "Instagram Reels", "X Thread"],
    predictedReach: "250k+",
    format: "Long-form + Shorts",
    trendMatch: 94,
    bestTime: "7:00 PM",
    audienceType: "Gen-Z (65%)",
    contentType: "Vlog",
    engagementScore: 91,
    tags: ["#DayInMyLife", "#CreatorLife", "#BehindTheScenes"],
  },
  {
    id: 2,
    title: '"5 Tools I Use to Scale My Creator Business"',
    reason:
      "Tool-based tutorials are trending +38% in your niche. Your audience engagement on \"how-to\" content is 2x higher.",
    platforms: ["YouTube", "Instagram Carousel"],
    predictedReach: "180k+",
    format: "Tutorial + Carousel",
    trendMatch: 87,
    bestTime: "8:30 AM",
    audienceType: "Millennial (42%)",
    contentType: "Tutorial",
    engagementScore: 84,
    tags: ["#CreatorTools", "#ContentCreator", "#BusinessTips"],
  },
  {
    id: 3,
    title: '"Reacting to My First YouTube Video (1M Subscriber Special)"',
    reason:
      "Milestone celebration content gets 3x average shares. Your community has been requesting this for 2 months.",
    platforms: ["YouTube", "X"],
    predictedReach: "400k+",
    format: "Reaction + Community",
    trendMatch: 97,
    bestTime: "6:00 PM",
    audienceType: "All segments",
    contentType: "Milestone",
    engagementScore: 98,
    tags: ["#1MilSubs", "#Milestone", "#ThankYou"],
  },
];

// ─── Performance Analytics ───────────────────────────────────────────────────
export const performanceData = [
  { week: "W1", youtube: 42000, instagram: 21000, x: 15000 },
  { week: "W2", youtube: 58000, instagram: 29000, x: 22000 },
  { week: "W3", youtube: 51000, instagram: 34000, x: 18000 },
  { week: "W4", youtube: 76000, instagram: 41000, x: 31000 },
  { week: "W5", youtube: 68000, instagram: 38000, x: 28000 },
  { week: "W6", youtube: 89000, instagram: 52000, x: 43000 },
];

export const topVideos = [
  {
    id: 1,
    title: "How I Made $50k in 1 Month as a Creator",
    platform: "YouTube",
    views: "1.2M",
    likes: "84k",
    comments: "6.2k",
    revenue: "$3,200",
    thumbnail: "https://picsum.photos/seed/vid1/120/68",
    publishedAt: "Apr 12, 2026",
    watchHours: "82k",
  },
  {
    id: 2,
    title: "I Tried Every AI Writing Tool So You Don't Have To",
    platform: "YouTube",
    views: "892k",
    likes: "61k",
    comments: "4.1k",
    revenue: "$2,700",
    thumbnail: "https://picsum.photos/seed/vid2/120/68",
    publishedAt: "Apr 5, 2026",
    watchHours: "64k",
  },
  {
    id: 3,
    title: "Day 1 of Building in Public — No Shortcuts",
    platform: "Instagram",
    views: "541k",
    likes: "48k",
    comments: "2.8k",
    revenue: "$900",
    thumbnail: "https://picsum.photos/seed/vid3/120/68",
    publishedAt: "Mar 28, 2026",
    watchHours: "—",
  },
];

// ─── Deals / Business Manager ────────────────────────────────────────────────
export const deals = [
  {
    id: 1,
    brand: "TechNova",
    logo: "TN",
    logoColor: "bg-blue-900/50 border-blue-800",
    logoIcon: "text-blue-400",
    amount: 4500,
    status: "pending_payment",
    statusLabel: "Payment Pending",
    statusColor: "text-yellow-400 bg-yellow-500/10 border-yellow-500/20",
    platform: "YouTube",
    deliverable: "1x Integration Video",
    dueDate: "May 10, 2026",
    contactEmail: "partnerships@technova.io",
    notes: "Invoice sent. Awaiting NET-30 payment.",
  },
  {
    id: 2,
    brand: "EcoStyle",
    logo: "ES",
    logoColor: "bg-emerald-900/50 border-emerald-800",
    logoIcon: "text-emerald-400",
    amount: 2000,
    status: "action_needed",
    statusLabel: "Action Needed",
    statusColor: "text-red-400 bg-red-400/10 border-red-400/20",
    platform: "Instagram",
    deliverable: "3x Story Posts + 1x Reel",
    dueDate: "May 2, 2026",
    contactEmail: "collab@ecostyle.co",
    notes: "Draft due tomorrow. Creative brief attached.",
  },
  {
    id: 3,
    brand: "SneakerHead Co.",
    logo: "SN",
    logoColor: "bg-purple-900/50 border-purple-800",
    logoIcon: "text-purple-400",
    amount: 7500,
    status: "new_request",
    statusLabel: "New Request",
    statusColor: "text-purple-400 bg-purple-400/10 border-purple-400/20",
    platform: "YouTube + Instagram",
    deliverable: "2x Sponsored Reels",
    dueDate: "May 20, 2026",
    contactEmail: "media@sneakerhead.co",
    notes: "New inquiry via email. Review & respond.",
  },
  {
    id: 4,
    brand: "GameStream",
    logo: "GS",
    logoColor: "bg-gray-800 border-gray-700",
    logoIcon: "text-gray-400",
    amount: 8000,
    status: "completed",
    statusLabel: "Paid",
    statusColor: "text-emerald-400 bg-emerald-400/10 border-emerald-400/20",
    platform: "YouTube",
    deliverable: "1x Sponsorship Segment",
    dueDate: "Apr 1, 2026",
    contactEmail: "sponsors@gamestream.gg",
    notes: "Completed. Payment received.",
  },
  {
    id: 5,
    brand: "HealthKit Pro",
    logo: "HK",
    logoColor: "bg-orange-900/50 border-orange-800",
    logoIcon: "text-orange-400",
    amount: 3200,
    status: "in_review",
    statusLabel: "In Review",
    statusColor: "text-orange-400 bg-orange-400/10 border-orange-400/20",
    platform: "Instagram",
    deliverable: "2x Feed Posts",
    dueDate: "May 15, 2026",
    contactEmail: "brand@healthkitpro.com",
    notes: "Contract under legal review.",
  },
];

export const paymentSummary = {
  totalEarned: "$127,400",
  pendingPayments: "$24,500",
  avgDealValue: "$5,200",
  dealsThisMonth: 3,
};

// ─── Inbox / CRM ─────────────────────────────────────────────────────────────
export const inboxMessages = [
  {
    id: 1,
    from: "Sarah K.",
    avatar: "https://i.pravatar.cc/40?img=1",
    platform: "youtube",
    type: "comment",
    message: "This video literally changed my life. Can you make more on this topic?",
    time: "2m ago",
    read: false,
    tag: "top_fan",
  },
  {
    id: 2,
    from: "TechNova PR",
    avatar: "https://i.pravatar.cc/40?img=5",
    platform: "email",
    type: "brand_dm",
    message: "Hi! We'd love to discuss a partnership opportunity for Q3. Are you available?",
    time: "18m ago",
    read: false,
    tag: "brand",
  },
  {
    id: 3,
    from: "Marcus J.",
    avatar: "https://i.pravatar.cc/40?img=3",
    platform: "instagram",
    type: "dm",
    message: "Your latest reel hit different bro! Followed instantly 🔥",
    time: "45m ago",
    read: false,
    tag: null,
  },
  {
    id: 4,
    from: "Priya M.",
    avatar: "https://i.pravatar.cc/40?img=9",
    platform: "youtube",
    type: "comment",
    message: "Question: what camera do you use? The quality is insane.",
    time: "1h ago",
    read: true,
    tag: null,
  },
  {
    id: 5,
    from: "NikeStyle Collab",
    avatar: "https://i.pravatar.cc/40?img=7",
    platform: "email",
    type: "brand_dm",
    message: "Following up on our previous conversation about the summer campaign...",
    time: "2h ago",
    read: true,
    tag: "brand",
  },
  {
    id: 6,
    from: "Jordan T.",
    avatar: "https://i.pravatar.cc/40?img=11",
    platform: "instagram",
    type: "dm",
    message: "When is the merch dropping?? I've been waiting so long!!",
    time: "3h ago",
    read: true,
    tag: "top_fan",
  },
  {
    id: 7,
    from: "Alex R.",
    avatar: "https://i.pravatar.cc/40?img=13",
    platform: "youtube",
    type: "comment",
    message: "Finally someone who explains this clearly. Subscribed and sharing!",
    time: "5h ago",
    read: true,
    tag: "top_fan",
  },
];

// ─── Fan CRM ─────────────────────────────────────────────────────────────────
export const topFans = [
  {
    id: 1,
    name: "Sarah K.",
    avatar: "https://i.pravatar.cc/80?img=1",
    handle: "@sarahk_creates",
    platform: "youtube",
    tier: "Super Fan",
    tierColor: "text-yellow-400 bg-yellow-400/10 border-yellow-400/30",
    totalLikes: "1.2k",
    comments: 342,
    shares: 89,
    memberSince: "Jan 2024",
    lastInteraction: "2 hours ago",
    engagementScore: 98,
    country: "🇺🇸 USA",
    segment: "Power User",
  },
  {
    id: 2,
    name: "Marcus J.",
    avatar: "https://i.pravatar.cc/80?img=3",
    handle: "@marcusbuilds",
    platform: "instagram",
    tier: "Top Fan",
    tierColor: "text-purple-400 bg-purple-400/10 border-purple-400/30",
    totalLikes: "847",
    comments: 201,
    shares: 54,
    memberSince: "Mar 2024",
    lastInteraction: "45 min ago",
    engagementScore: 91,
    country: "🇬🇧 UK",
    segment: "Engaged",
  },
  {
    id: 3,
    name: "Priya M.",
    avatar: "https://i.pravatar.cc/80?img=9",
    handle: "@priya_designs",
    platform: "youtube",
    tier: "Top Fan",
    tierColor: "text-purple-400 bg-purple-400/10 border-purple-400/30",
    totalLikes: "712",
    comments: 178,
    shares: 41,
    memberSince: "Apr 2024",
    lastInteraction: "1 hour ago",
    engagementScore: 87,
    country: "🇮🇳 India",
    segment: "Engaged",
  },
  {
    id: 4,
    name: "Jordan T.",
    avatar: "https://i.pravatar.cc/80?img=11",
    handle: "@jordantech_",
    platform: "x",
    tier: "Loyal Fan",
    tierColor: "text-blue-400 bg-blue-400/10 border-blue-400/30",
    totalLikes: "509",
    comments: 134,
    shares: 67,
    memberSince: "Jun 2024",
    lastInteraction: "3 hours ago",
    engagementScore: 79,
    country: "🇨🇦 Canada",
    segment: "Casual",
  },
  {
    id: 5,
    name: "Alex R.",
    avatar: "https://i.pravatar.cc/80?img=13",
    handle: "@alexr_film",
    platform: "youtube",
    tier: "Loyal Fan",
    tierColor: "text-blue-400 bg-blue-400/10 border-blue-400/30",
    totalLikes: "486",
    comments: 122,
    shares: 33,
    memberSince: "Jul 2024",
    lastInteraction: "5 hours ago",
    engagementScore: 76,
    country: "🇦🇺 Australia",
    segment: "Casual",
  },
  {
    id: 6,
    name: "Camila F.",
    avatar: "https://i.pravatar.cc/80?img=16",
    handle: "@camilacreates",
    platform: "instagram",
    tier: "Loyal Fan",
    tierColor: "text-blue-400 bg-blue-400/10 border-blue-400/30",
    totalLikes: "421",
    comments: 98,
    shares: 28,
    memberSince: "Aug 2024",
    lastInteraction: "8 hours ago",
    engagementScore: 72,
    country: "🇧🇷 Brazil",
    segment: "Casual",
  },
];

export const fanSegments = [
  { name: "Super Fans", count: 12, color: "bg-yellow-400", pct: 2 },
  { name: "Top Fans", count: 284, color: "bg-purple-500", pct: 8 },
  { name: "Loyal Fans", count: 1820, color: "bg-blue-500", pct: 52 },
  { name: "Casual Followers", count: 1340, color: "bg-gray-600", pct: 38 },
];

export const audienceInsights = {
  ageGroups: [
    { group: "13–17", pct: 8 },
    { group: "18–24", pct: 38 },
    { group: "25–34", pct: 29 },
    { group: "35–44", pct: 15 },
    { group: "45+", pct: 10 },
  ],
  genderSplit: { male: 54, female: 44, other: 2 },
  topCountries: [
    { country: "🇺🇸 USA", pct: 34 },
    { country: "🇮🇳 India", pct: 18 },
    { country: "🇬🇧 UK", pct: 12 },
    { country: "🇧🇷 Brazil", pct: 9 },
    { country: "🇨🇦 Canada", pct: 7 },
  ],
  peakHours: ["7 PM", "8 PM", "9 PM"],
};
